//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace PSIMP.Models
{
	using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class AM_ApplicationRepliedDetail : BaseEntity
    {
        //主键被写在BaseEntity中,已忽略生成
        //public Guid ID{ get; set; }
        public System.Guid RepliedPersonID { get; set; }
        public bool RepliedResult { get; set; }
        public string RepliedSuggestion { get; set; }
        public System.DateTime RepliedDate { get; set; }
        public string RepliedPersonPosition { get; set; }
        public string RepliedDepartment { get; set; }
        public bool RepliedStatus { get; set; }
    }
}
