//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace PSIMP.Models
{
	using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class AM_ApplicationContent_CapitalFundCategory : BaseEntity
    {
        //主键被写在BaseEntity中,已忽略生成
        //public Guid ID{ get; set; }
        public System.Guid ProjectApplicationID { get; set; }
        public string ApplicationType { get; set; }
        public string AssetName { get; set; }
        public string SpecificationMode { get; set; }
        public int Quantity { get; set; }
        public string Unit { get; set; }
        public decimal Money { get; set; }
        public decimal TotalMoney { get; set; }
        public string Description { get; set; }
    
        public virtual AM_ProjectApplicationBaseInfo AM_ProjectApplicationBaseInfo { get; set; }
    }
}
