//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace PSIMP.Models
{
	using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class AM_ProjectApplicationBaseInfo
    {
        public AM_ProjectApplicationBaseInfo()
        {
            this.AM_ApplicationContent_CapitalFundCategory = new HashSet<AM_ApplicationContent_CapitalFundCategory>();
            this.AM_ApplicationContent_VehicleCategory = new HashSet<AM_ApplicationContent_VehicleCategory>();
        }
    
        public System.Guid ProjectApplicationID { get; set; }
        public string ApplicationSerialNumber { get; set; }
        public System.DateTime ApplicationDate { get; set; }
        public System.Guid ApplicationProjectID { get; set; }
        public System.Guid ApplicationPersonID { get; set; }
        public string ApplicationReason { get; set; }
        public string ApplicationContent { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<AM_ApplicationContent_CapitalFundCategory> AM_ApplicationContent_CapitalFundCategory { get; set; }
        public virtual ICollection<AM_ApplicationContent_VehicleCategory> AM_ApplicationContent_VehicleCategory { get; set; }
    }
}
