//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace PSIMP.Models
{
	using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class AMG_AssetBaseInfo : BaseEntity
    {
        public AMG_AssetBaseInfo()
        {
            this.AMG_AssetAllocateInfo = new HashSet<AMG_AssetAllocateInfo>();
            this.AMG_AssetRepairInfo = new HashSet<AMG_AssetRepairInfo>();
            this.AMG_AssetUseInfo = new HashSet<AMG_AssetUseInfo>();
        }
    
        //主键被写在BaseEntity中,已忽略生成
        //public Guid ID{ get; set; }
        public string AssetSerialNumber { get; set; }
        public int AssetType { get; set; }
        public string AssetName { get; set; }
        public string AssetSpecificationModel { get; set; }
        public string Unit { get; set; }
        public System.DateTime BuyDate { get; set; }
        public int Quantity { get; set; }
        public decimal UnitPrice { get; set; }
        public decimal SumPrice { get; set; }
        public int AssetStatus { get; set; }
        public string Description { get; set; }
        public string Other1 { get; set; }
        public string Other2 { get; set; }
        public string Other3 { get; set; }
    
        public virtual ICollection<AMG_AssetAllocateInfo> AMG_AssetAllocateInfo { get; set; }
        public virtual ICollection<AMG_AssetRepairInfo> AMG_AssetRepairInfo { get; set; }
        public virtual ICollection<AMG_AssetUseInfo> AMG_AssetUseInfo { get; set; }
    }
}
