//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace PSIMP.Models
{
	using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class EM_ProjectTestPutOnFile
    {
        public string TestPutonFileID { get; set; }
        public string ProjectID { get; set; }
        public string ProjectName { get; set; }
        public System.DateTime PutonfileStartDate { get; set; }
        public System.DateTime PutonfileEndDate { get; set; }
        public short PutonfileTimes { get; set; }
        public string Description { get; set; }
    
        public virtual EM_ProjectBaseInfo EM_ProjectBaseInfo { get; set; }
    }
}
