//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace PSIMP.Models
{
	using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class EM_ProjectContractBaseInfo : BaseEntity
    {
        public EM_ProjectContractBaseInfo()
        {
            this.EM_ProjectContractDataInfo = new HashSet<EM_ProjectContractDataInfo>();
            this.EM_ProjectContractPayCondition = new HashSet<EM_ProjectContractPayCondition>();
            this.EM_ProjectContractPersonInfo = new HashSet<EM_ProjectContractPersonInfo>();
            this.EM_ProjectExpandInfo = new HashSet<EM_ProjectExpandInfo>();
        }
    
        //主键被写在BaseEntity中,已忽略生成
        //public Guid ID{ get; set; }
        public System.Guid ProjectID { get; set; }
        public System.DateTime BiddingDate { get; set; }
        public int ContractPeriod { get; set; }
        public System.DateTime OpenDate { get; set; }
        public int OpeningPeriod { get; set; }
        public string OpeningConditions { get; set; }
        public string Description { get; set; }
        public byte ContractAttachment { get; set; }
    
        public virtual EM_ProjectBaseInfo EM_ProjectBaseInfo { get; set; }
        public virtual ICollection<EM_ProjectContractDataInfo> EM_ProjectContractDataInfo { get; set; }
        public virtual ICollection<EM_ProjectContractPayCondition> EM_ProjectContractPayCondition { get; set; }
        public virtual ICollection<EM_ProjectContractPersonInfo> EM_ProjectContractPersonInfo { get; set; }
        public virtual ICollection<EM_ProjectExpandInfo> EM_ProjectExpandInfo { get; set; }
    }
}
