//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace PSIMP.Models
{
	using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class EM_ProjectBaseInfo : BaseEntity
    {
        public EM_ProjectBaseInfo()
        {
            this.EM_ProjectContractBaseInfo = new HashSet<EM_ProjectContractBaseInfo>();
            this.EM_ProjectPersonManage = new HashSet<EM_ProjectPersonManage>();
            this.EM_ProjectContractPerformance = new HashSet<EM_ProjectContractPerformance>();
            this.EM_ProjectTestPutOnFile = new HashSet<EM_ProjectTestPutOnFile>();
        }
    
        //主键被写在BaseEntity中,已忽略生成
        //public Guid ID{ get; set; }
        public string ProjectFullName { get; set; }
        public string ProjectName { get; set; }
        public string ConstructionCompany { get; set; }
        public System.Guid ProjectType { get; set; }
        public float ProjectScale { get; set; }
        public string ProjectAddress { get; set; }
        public System.DateTime EntryDate { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime FinishedDate { get; set; }
        public System.DateTime CompletionDate { get; set; }
        public int ConstructionPeriod { get; set; }
        public int DefectsLiabilityPeriod { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<EM_ProjectContractBaseInfo> EM_ProjectContractBaseInfo { get; set; }
        public virtual ICollection<EM_ProjectPersonManage> EM_ProjectPersonManage { get; set; }
        public virtual ICollection<EM_ProjectContractPerformance> EM_ProjectContractPerformance { get; set; }
        public virtual ICollection<EM_ProjectTestPutOnFile> EM_ProjectTestPutOnFile { get; set; }
    }
}
