//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace PSIMP.Models
{
	using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class PM_PersonTrainingExperience
    {
        public System.Guid ID { get; set; }
        public string InstitutionsName { get; set; }
        public System.DateTime TrainingStartDate { get; set; }
        public System.DateTime TrainingEndDate { get; set; }
        public string TrainingAddress { get; set; }
        public string TrainingContent { get; set; }
        public string GotCertificate { get; set; }
        public string Descriptions { get; set; }
    }
}
