//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace PSIMP.Models
{
	using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class VM_VehicleLeaseInfo : BaseEntity
    {
        //主键被写在BaseEntity中,已忽略生成
        //public Guid ID{ get; set; }
        public System.Guid VehicleID { get; set; }
        public int ContractStatus { get; set; }
        public System.DateTime ContractStartDate { get; set; }
        public System.DateTime ContractEndDate { get; set; }
        public decimal MonthlyLeaseMoney { get; set; }
        public string LeasePersonName { get; set; }
        public string LeasePersonPhoneNum { get; set; }
        public System.DateTime PurchaseDate { get; set; }
        public bool IsMailToCompany { get; set; }
        public string Description { get; set; }
        public byte ContractAttachment { get; set; }
    
        public virtual VM_VehicleBaseInfo VM_VehicleBaseInfo { get; set; }
    }
}
