//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace PSIMP.Models
{
	using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class VM_VehicleRepairDetailList
    {
        public System.Guid ID { get; set; }
        public System.Guid VehicleRepairID { get; set; }
        public System.Guid VehicleID { get; set; }
        public string PartsName { get; set; }
        public int Quantity { get; set; }
        public decimal ApplicationUnitprice { get; set; }
        public decimal ApplicationCost { get; set; }
        public decimal CheckUnitPrice { get; set; }
        public decimal CheckCost { get; set; }
        public decimal RealityUnitprice { get; set; }
        public decimal RealityCost { get; set; }
        public decimal LaborCost { get; set; }
        public string Description { get; set; }
    
        public virtual VM_VehicleRepair VM_VehicleRepair { get; set; }
    }
}
