//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSIMP.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menus
    {
        public Menus()
        {
            this.Items = new HashSet<Menus>();
        }
    
        public long ID { get; set; }
        public string Name { get; set; }
        public string Summary { get; set; }
        public string AreaName { get; set; }
        public string ControllerName { get; set; }
        public string ActionName { get; set; }
        public string Paramater { get; set; }
        public string IconCls { get; set; }
        public Nullable<long> MenusID { get; set; }
    
        public virtual ICollection<Menus> Items { get; set; }
        public virtual Menus ParentMenu { get; set; }
    }
}
