//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace PSIMP.Models
{
	using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class AMG_AssetRepairInfo : BaseEntity
    {
        //主键被写在BaseEntity中,已忽略生成
        //public Guid ID{ get; set; }
        public System.Guid AssetBaseInfoID { get; set; }
        public int RepairType { get; set; }
        public string RepairReason { get; set; }
        public decimal RepairMoney { get; set; }
        public System.DateTime RepairDate { get; set; }
        public System.Guid OperationUserID { get; set; }
        public string Description { get; set; }
        public string Other1 { get; set; }
        public int Other2 { get; set; }
    
        public virtual AMG_AssetBaseInfo AMG_AssetBaseInfo { get; set; }
    }
}
