//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace PSIMP.Models
{
	using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class EM_ProjectContractPersonInfo
    {
        public System.Guid ContractPersonID { get; set; }
        public string ProjectContractID { get; set; }
        public string ContractDuties { get; set; }
        public string PersonID { get; set; }
        public string ContractPosition { get; set; }
        public string HoldCertificate { get; set; }
        public string Other { get; set; }
        public string Description { get; set; }
    
        public virtual EM_ProjectContractBaseInfo EM_ProjectContractBaseInfo { get; set; }
    }
}
