//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace PSIMP.Models
{
	using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class EM_ProjectContractPerformance
    {
        public int ProjectContractPerformanceID { get; set; }
        public string ProjectID { get; set; }
        public string PersonID { get; set; }
        public string PersonName { get; set; }
        public string OnProjectID { get; set; }
        public string InPresentDate { get; set; }
        public string PerformanceProjectID { get; set; }
        public string PerformanceDuties { get; set; }
        public string OutDate { get; set; }
        public string Description { get; set; }
    
        public virtual EM_ProjectBaseInfo EM_ProjectBaseInfo { get; set; }
    }
}
