//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace PSIMP.Models
{
	using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class EM_ProjectContractPayCondition
    {
        public System.Guid PContractPayConditionID { get; set; }
        public string ContractID { get; set; }
        public string MeasurePayCondition { get; set; }
        public string AgainstRiskPayCondition { get; set; }
        public string GuaranteePayMoney { get; set; }
        public string GuaranteePayCondition { get; set; }
        public string MobilizeAdvanceMoneyLetter { get; set; }
        public string PerformanceBondPayCondition { get; set; }
        public string PayMode { get; set; }
        public string PayDutyMode { get; set; }
    
        public virtual EM_ProjectContractBaseInfo EM_ProjectContractBaseInfo { get; set; }
    }
}
