//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace PSIMP.Models
{
	using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class EM_ProjectPersonManage
    {
        public System.Guid ProjectPersonID { get; set; }
        public string ProjectID { get; set; }
        public string ProjectName { get; set; }
        public string DutiesName { get; set; }
        public string PersonID { get; set; }
        public string PersonName { get; set; }
        public string PersonComeType { get; set; }
        public string IsOnScene { get; set; }
        public string EntryDate { get; set; }
        public string ProjectPosition { get; set; }
        public string ExitDate { get; set; }
        public string ExitReason { get; set; }
        public string IsHaveOwnerReplied { get; set; }
        public string RepliedDate { get; set; }
        public string RepliedResult { get; set; }
        public string RepliedSuggestion { get; set; }
        public string RepliedNumber { get; set; }
        public string RepliedAttachment { get; set; }
        public string Description { get; set; }
    
        public virtual EM_ProjectBaseInfo EM_ProjectBaseInfo { get; set; }
    }
}
