//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace PSIMP.Models
{
	using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class PM_CertificateManage
    {
        public System.Guid CertificateID { get; set; }
        public string FileNumber { get; set; }
        public string PersonID { get; set; }
        public System.DateTime RegisterDate { get; set; }
        public string ProjectID { get; set; }
        public string PositionStatus { get; set; }
        public string SubmitCorporationDate { get; set; }
        public string IsSubmitGraduationCertificate { get; set; }
        public string IsSubmitSupervisionCertificate { get; set; }
        public string IsSubmitPositionalCertificate { get; set; }
        public string IsSubmitSecurityCertificate { get; set; }
        public string IsSubmitConservationCertificate { get; set; }
        public string IsSubmitIdentificationCard { get; set; }
        public string ReturnBusinessUnitDate { get; set; }
        public string IsReturnGraduationCertificate { get; set; }
        public string IsReturnSupervisionCertificate { get; set; }
        public string IsReturnPositionalCertificate { get; set; }
        public string IsReturnSecurityCertificate { get; set; }
        public string IsReturnConservationCertificate { get; set; }
        public string IsReturnIdentificationCard { get; set; }
        public string GivebackSelfDate { get; set; }
        public string IsGivebackGraduationCertificate { get; set; }
        public string IsGivebackSupervisionCertificate { get; set; }
        public string IsGivebackPositionalCertificate { get; set; }
        public string IsGivebackSecurityCertificate { get; set; }
        public string IsGivebackConservationCertificate { get; set; }
        public string IsGivebackIdentificationCard { get; set; }
        public string Descriptions { get; set; }
    }
}
