//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace PSIMP.Models
{
	using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class PM_PersonBaseInfo
    {
        public PM_PersonBaseInfo()
        {
            this.Sex = true;
        }
    
        public string PersonID { get; set; }
        public string PersonName { get; set; }
        public bool Sex { get; set; }
        public System.DateTime Birthday { get; set; }
        public string IDNumber { get; set; }
        public string RegisterAddress { get; set; }
        public string ContactNumber { get; set; }
        public string AlternateNumber { get; set; }
        public byte TwoInchPhoto { get; set; }
    }
}
