//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace PSIMP.Models
{
	using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Train : Psimp
    {
        public string Agency { get; set; }
        public string DateTime { get; set; }
        public string Location { get; set; }
        public string Curriculum { get; set; }
        public string Certificate { get; set; }
        public string Details { get; set; }
        public string CertDetails { get; set; }
        public long PersonId { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
