//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace PSIMP.Models
{
	using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class UserFiles
    {
        public UserFiles()
        {
            this.IsShared = false;
        }
    
        public long ID { get; set; }
        public string FileName { get; set; }
        public string FileType { get; set; }
        public string FileSize { get; set; }
        public string Remark { get; set; }
        public bool IsShared { get; set; }
        public long FolderID { get; set; }
        public string SharedRemark { get; set; }
    
        public virtual UserFolders UserFolder { get; set; }
    }
}
