//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace PSIMP.Models
{
	using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class VM_VehicleBaseInfo : BaseEntity
    {
        public VM_VehicleBaseInfo()
        {
            this.VM_VehicleAllocateInfo = new HashSet<VM_VehicleAllocateInfo>();
            this.VM_VehicleLeaseInfo = new HashSet<VM_VehicleLeaseInfo>();
            this.VM_VehicleUseInfo = new HashSet<VM_VehicleUseInfo>();
            this.VM_VehicleYearInspection = new HashSet<VM_VehicleYearInspection>();
            this.VM_VehicleOperatingCost = new HashSet<VM_VehicleOperatingCost>();
            this.VM_VehicleLoanInfo = new HashSet<VM_VehicleLoanInfo>();
            this.VM_VehicleInsurance = new HashSet<VM_VehicleInsurance>();
            this.VM_VehicleRepair = new HashSet<VM_VehicleRepair>();
        }
    
        //主键被写在BaseEntity中,已忽略生成
        //public Guid ID{ get; set; }
        public string VehicleBrand { get; set; }
        public string MotorModelNumber { get; set; }
        public string VehicleLicensePlate { get; set; }
        public bool VehicleSource { get; set; }
        public bool PayMode { get; set; }
        public decimal BuyCost { get; set; }
        public string VehicleOwner { get; set; }
        public string DrivingLicense { get; set; }
        public System.DateTime BuyDate { get; set; }
        public int UseStatus { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<VM_VehicleAllocateInfo> VM_VehicleAllocateInfo { get; set; }
        public virtual ICollection<VM_VehicleLeaseInfo> VM_VehicleLeaseInfo { get; set; }
        public virtual ICollection<VM_VehicleUseInfo> VM_VehicleUseInfo { get; set; }
        public virtual ICollection<VM_VehicleYearInspection> VM_VehicleYearInspection { get; set; }
        public virtual ICollection<VM_VehicleOperatingCost> VM_VehicleOperatingCost { get; set; }
        public virtual ICollection<VM_VehicleLoanInfo> VM_VehicleLoanInfo { get; set; }
        public virtual ICollection<VM_VehicleInsurance> VM_VehicleInsurance { get; set; }
        public virtual ICollection<VM_VehicleRepair> VM_VehicleRepair { get; set; }
    }
}
