//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace PSIMP.Models
{
	using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class VM_VehicleLoanInfo
    {
        public VM_VehicleLoanInfo()
        {
            this.VM_PaymentDetailInfo = new HashSet<VM_PaymentDetailInfo>();
        }
    
        public System.Guid VehicleLoanID { get; set; }
        public System.Guid VehicleID { get; set; }
        public string Borrowers { get; set; }
        public string GuaranteeUnitName { get; set; }
        public string GuaranteeUnitPhone { get; set; }
        public decimal GuaranteeMoney { get; set; }
        public decimal LoanDeposit { get; set; }
        public decimal LoanSum { get; set; }
        public decimal LoanInterest { get; set; }
        public decimal LoanTotalSum { get; set; }
        public float DownPaymentRatio { get; set; }
        public decimal DownPayment { get; set; }
        public int LoanPeriod { get; set; }
        public float YearRate { get; set; }
        public System.DateTime StatementDate { get; set; }
        public decimal MonthlyPaymentMoney { get; set; }
        public string PaymentBankName { get; set; }
        public string PaymentBankAccountNum { get; set; }
        public System.DateTime PaymentStartDate { get; set; }
        public System.DateTime PaymentDueDate { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<VM_PaymentDetailInfo> VM_PaymentDetailInfo { get; set; }
        public virtual VM_VehicleBaseInfo VM_VehicleBaseInfo { get; set; }
    }
}
