//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace PSIMP.Models
{
	using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class VM_VehicleRepair : BaseEntity
    {
        public VM_VehicleRepair()
        {
            this.VM_VehicleRepairDetailList = new HashSet<VM_VehicleRepairDetailList>();
        }
    
        //主键被写在BaseEntity中,已忽略生成
        //public Guid ID{ get; set; }
        public System.Guid VehicleID { get; set; }
        public string ApplicationSerialNumber { get; set; }
        public float MileageNumber { get; set; }
        public System.DateTime RepairDate { get; set; }
        public int RepairGrade { get; set; }
        public string RepairFactoryName { get; set; }
        public string RepairPhoneNumber { get; set; }
        public string Other1 { get; set; }
        public string Other2 { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<VM_VehicleRepairDetailList> VM_VehicleRepairDetailList { get; set; }
        public virtual VM_VehicleBaseInfo VM_VehicleBaseInfo { get; set; }
    }
}
