//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace PSIMP.Models
{
    using System;
    using System.Collections.Generic;
    using PSIMP.Business.BaseModel;
    
    public partial class EM_ProjectContractBaseInfo : BaseEntity
    {
        public System.DateTime BiddingDate { get; set; }
        /// <summary>
        /// 合同工期
        /// </summary>
        public int ContractPeriod { get; set; }
        public DateTime OpenDate { get; set; }
        /// <summary>
        /// 开口期限
        /// </summary>
        public int OpeningPeriod { get; set; }
        public string OpeningConditions { get; set; }
        public string Description { get; set; }
        /// <summary>
        /// 合同附件
        /// </summary>
        public string ContractAttachment { get; set; }
    
        public virtual EM_ProjectBaseInfo EM_ProjectBaseInfo { get; set; }
        public virtual ICollection<EM_ProjectContractDataInfo> EM_ProjectContractDataInfo { get; set; }
        public virtual ICollection<EM_ProjectContractPayCondition> EM_ProjectContractPayCondition { get; set; }
        public virtual ICollection<EM_ProjectContractPersonInfo> EM_ProjectContractPersonInfo { get; set; }
        public virtual ICollection<EM_ProjectExpandInfo> EM_ProjectExpandInfo { get; set; }
    }
}
