//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace PSIMP.Models
{
    using System;
    using System.Collections.Generic;
    using PSIMP.Business.BaseModel;
    
    public partial class EM_ProjectContractPersonInfo : BaseEntity
    {
        public string ContractDuties { get; set; }
        public string ContractPosition { get; set; }
        public string HoldCertificate { get; set; }
        public string Other { get; set; }
        public string Description { get; set; }
    
        public virtual EM_ProjectContractBaseInfo EM_ProjectContractBaseInfo { get; set; }
        public virtual PM_PersonBaseInfo PM_PersonBaseInfo { get; set; }
    }
}
