//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace PSIMP.Models
{
    using System;
    using System.Collections.Generic;
    using PSIMP.Business.BaseModel;
    
    public partial class AM_ApplicationContent_CapitalFundCategory : BaseEntity
    {
        /// <summary>
        /// 资产类申请类别,详见枚举：AssetApplicationType
        /// </summary>
        public int ApplicationType { get; set; }
        //public string AssetName { get; set; }
        //public string SpecificationMode { get; set; }
        public int Quantity { get; set; }
        public string Unit { get; set; }
        public decimal Money { get; set; }
        public decimal TotalMoney { get; set; }
        public string Description { get; set; }
        public virtual AMG_AssetBaseInfo AMG_AssetBaseInfo { get; set; }
        public virtual AM_ProjectApplicationBaseInfo AM_ProjectApplicationBaseInfo { get; set; }
    }
}
