//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace PSIMP.Models
{
    using System;
    using System.Collections.Generic;
    using PSIMP.Business.BaseModel;
    
    public partial class AM_ApplicationContent_VehicleCategory : BaseEntity
    {
        /// <summary>
        /// 车辆类申请类别,见枚举
        /// </summary>
        public int ApplicationType { get; set; }
        //public string PlateNumber { get; set; }
        public string Mileage { get; set; }
        public string CarPart { get; set; }
        public string ItemName { get; set; }
        public decimal ItemMoney { get; set; }
        public int ItemQuantity { get; set; }
        public decimal TotalMoney { get; set; }
        public string Description { get; set; }
        public virtual VM_VehicleBaseInfo VM_VehicleBaseInfo { get; set; }
        public virtual AM_ProjectApplicationBaseInfo AM_ProjectApplicationBaseInfo { get; set; }
    }
}
