//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace PSIMP.Models
{
    using System;
    using System.Collections.Generic;
    using PSIMP.Business.BaseModel;
    
    public partial class PM_PersonInsuranceInfo : BaseEntity
    {
        public string InsuranceNumber { get; set; }
        /// <summary>
        /// 保险类别
        /// </summary>
        public string InsuranceType { get; set; }
        public DateTime EffectiveDate { get; set; }
        public DateTime ExpiryDate { get; set; }
        /// <summary>
        /// 在职状态(true:在职,false：不在)
        /// </summary>
        public bool PositionStatus { get; set; }
        public string InsuredNumber { get; set; }
        public string InsuranceContent { get; set; }
        
        /// <summary>
        /// 目前岗位
        /// </summary>
        public string PositionName { get; set; }
        //public int InsuranceStatus { get; set; }
        public string Description { get; set; }
    
        public virtual PM_PersonBaseInfo PM_PersonBaseInfo { get; set; }
        /// <summary>
        /// 所在项目
        /// </summary>
        public virtual EM_ProjectBaseInfo EM_ProjectBaseInfo { get; set; }
    }
}
