//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using PSIMP.Business.BaseModel;

namespace PSIMP.Models
{
   
    
    public partial class PM_PersonTrainingExperience : BaseEntity
    {
        
        public string InstitutionsName { get; set; }
        public System.DateTime TrainingStartDate { get; set; }
        public System.DateTime TrainingEndDate { get; set; }
        public string TrainingAddress { get; set; }
        public string TrainingContent { get; set; }
        public string GotCertificate { get; set; }
        public string Descriptions { get; set; }
        public System.Guid PersonID { get; set; }
    
        public virtual PM_PersonBaseInfo PM_PersonBaseInfo { get; set; }
    }
}
