//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace PSIMP.Models
{
    using System;
    using System.Collections.Generic;
    using PSIMP.Business.BaseModel;
    
    public partial class PM_PersonContractInfo : BaseEntity
    {
        public string ContractNumber { get; set; }
        public DateTime? SignDate { get; set; }
        public DateTime? ContractBeginDate { get; set; }
        public DateTime? ContractEndDate { get; set; }
        /// <summary>
        /// 合同岗位
        /// </summary>
        public string ContractPosition { get; set; }
        public decimal ContractSalary { get; set; }
        public string Description { get; set; }
        public virtual PM_PersonBaseInfo PM_PersonBaseInfo { get; set; }
    }
}
