//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace PSIMP.Models
{
    using System;
    using System.Collections.Generic;
    using PSIMP.Business.BaseModel;
    
    public partial class EM_ProjectContractDataInfo : BaseEntity
    {
        public decimal ContractMoney { get; set; }
        public decimal ProvisionalSums { get; set; }
        public decimal ContractNetAmount { get; set; }
        public decimal ConstructionPeriodMoney { get; set; }
        public decimal DefectPeriodMoeny { get; set; }
        public decimal GuaranteePeriodMoney { get; set; }
        public decimal HonestDepositMoney { get; set; }
        public decimal GuaranteeMoney { get; set; }
        public decimal AgainstRiskMoney { get; set; }
        public decimal ReviewMoeny { get; set; }
        public System.Guid ContractID { get; set; }
    
        public virtual EM_ProjectContractBaseInfo EM_ProjectContractBaseInfo { get; set; }
    }
}
