//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace PSIMP.Models
{
    using System;
    using System.Collections.Generic;
    using PSIMP.Business.BaseModel;
    
    public partial class VM_VehicleBaseInfo : BaseEntity
    {
        /// <summary>
        /// 车辆品牌
        /// </summary>
        public string VehicleBrand { get; set; }
        public string MotorModelNumber { get; set; }
        public string VehicleLicensePlate { get; set; }
        /// <summary>
        /// 车辆来源,详见枚举：VehicleSource 
        /// </summary>
        public int VehicleSource { get; set; }
        /// <summary>
        /// 详见枚举：VehiclePayMode（车辆支付方式）
        /// </summary>
        public int PayMode { get; set; }
        public decimal BuyCost { get; set; }
        /// <summary>
        /// 车主人，若为分期则为承贷人或贷款人
        /// </summary>
        public string VehicleOwner { get; set; }
        public string DrivingLicense { get; set; }
        public DateTime? BuyDate { get; set; }
        /// <summary>
        /// 车辆状态，详见枚举:VehicleUseStatus
        /// </summary>
        public int UseStatus { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<VM_VehicleAllocateInfo> VM_VehicleAllocateInfo { get; set; }
        public virtual ICollection<VM_VehicleLeaseInfo> VM_VehicleLeaseInfo { get; set; }
        public virtual ICollection<VM_VehicleUseInfo> VM_VehicleUseInfo { get; set; }
        public virtual ICollection<VM_VehicleYearInspection> VM_VehicleYearInspection { get; set; }
        public virtual ICollection<VM_VehicleOperatingCost> VM_VehicleOperatingCost { get; set; }
        public virtual ICollection<VM_VehicleLoanInfo> VM_VehicleLoanInfo { get; set; }
        public virtual ICollection<VM_VehicleInsurance> VM_VehicleInsurance { get; set; }
        public virtual ICollection<VM_VehicleRepair> VM_VehicleRepair { get; set; }
    }
}
