//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace PSIMP.Models
{
    using System;
    using System.Collections.Generic;
    using PSIMP.Business.BaseModel;
    
    public partial class VM_VehicleRepairDetailList : BaseEntity
    {
        public string PartsName { get; set; }
        public int Quantity { get; set; }
        public decimal ApplicationUnitprice { get; set; }
        public decimal ApplicationCost { get; set; }
        public decimal CheckUnitPrice { get; set; }
        public decimal CheckCost { get; set; }
        public decimal RealityUnitprice { get; set; }
        public decimal RealityCost { get; set; }
        public decimal LaborCost { get; set; }
        public string Description { get; set; }
    
        public virtual VM_VehicleRepair VM_VehicleRepair { get; set; }
    }
}
