//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace PSIMP.Models
{
    using System;
    using System.Collections.Generic;
    using PSIMP.Business.BaseModel;
    
    public partial class VM_VehicleLeaseInfo : BaseEntity
    {
        /// <summary>
        /// 车辆租赁状态,详见枚举:VehicleLeaseStatus
        /// </summary>
        public int ContractStatus { get; set; }
        public DateTime ContractStartDate { get; set; }
        public DateTime ContractEndDate { get; set; }
        public decimal MonthlyLeaseMoney { get; set; }
        public string LeasePersonName { get; set; }
        public string LeasePersonPhoneNum { get; set; }
        public DateTime? PurchaseDate { get; set; }
        public bool IsMailToCompany { get; set; }
        public string Description { get; set; }
        /// <summary>
        /// 附件
        /// </summary>
        public string ContractAttachment { get; set; }
    
        public virtual VM_VehicleBaseInfo VM_VehicleBaseInfo { get; set; }
    }
}
