//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace PSIMP.Models
{
    using System;
    using System.Collections.Generic;
    using PSIMP.Business.BaseModel;
    /// <summary>
    /// 车辆使用信息
    /// </summary>
    public partial class VM_VehicleUseInfo : BaseEntity
    {
        /// <summary>
        /// 所在地点:成都公司、北京中通、监理项目
        /// </summary>
        public string UseAddress { get; set; }
        /// <summary>
        /// 使用对象：项目用车、业主用车
        /// </summary>
        public string VehicleUseType { get; set; }
        public string VehicleDriver { get; set; }
        public DateTime VehicleStartDate { get; set; }
        public DateTime VehicleEndDate { get; set; }
        public string UsePurpose { get; set; }
        public string Description { get; set; }
        public string Other { get; set; }
    
        public virtual VM_VehicleBaseInfo VM_VehicleBaseInfo { get; set; }
        public virtual ICollection<VM_VehicleOperatingCost> VM_VehicleOperatingCost { get; set; }
    }
}
