//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using PSIMP.Business.BaseModel;

namespace PSIMP.Models
{

    /// <summary>
    /// 贷款信息
    /// </summary>
    public partial class VM_VehicleLoanInfo : BaseEntity
    {
        public string Borrowers { get; set; }
        public string GuaranteeUnitName { get; set; }
        public string GuaranteeUnitPhone { get; set; }
        public decimal GuaranteeMoney { get; set; }
        public decimal LoanDeposit { get; set; }
        public decimal LoanSum { get; set; }
        public decimal LoanInterest { get; set; }
        public decimal LoanTotalSum { get; set; }
        /// <summary>
        /// 首付比列
        /// </summary>
        public decimal DownPaymentRatio { get; set; }
        /// <summary>
        /// 首付金额
        /// </summary>
        public decimal DownPayment { get; set; }
        public int LoanPeriod { get; set; }
        public decimal YearRate { get; set; }
        public DateTime StatementDate { get; set; }
        public decimal MonthlyPaymentMoney { get; set; }
        public string PaymentBankName { get; set; }
        public string PaymentBankAccountNum { get; set; }
        public DateTime PaymentStartDate { get; set; }
        public DateTime PaymentDueDate { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<VM_PaymentDetailInfo> VM_PaymentDetailInfo { get; set; }
        public virtual VM_VehicleBaseInfo VM_VehicleBaseInfo { get; set; }
    }
}
