//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace PSIMP.Models
{
    using System;
    using System.Collections.Generic;
    using PSIMP.Business.BaseModel;
    
    public partial class EM_ProjectContractPerformance : BaseEntity
    {
        public DateTime InPresentDate { get; set; }
        public string PerformanceDuties { get; set; }
        public DateTime OutDate { get; set; }
        public string Description { get; set; }
        /// <summary>
        /// 所在项目
        /// </summary>
        public virtual EM_ProjectBaseInfo EM_OnProject { get; set; }
        /// <summary>
        /// 履约项目
        /// </summary>
        public virtual EM_ProjectBaseInfo EM_PerformanceProject { get; set; }
        public virtual PM_PersonBaseInfo PM_PersonBaseInfo { get; set; }
    }
}
