//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace PSIMP.Models
{
    using System;
    using System.Collections.Generic;
    using PSIMP.Business.BaseModel;
    
    public partial class EM_ProjectPersonManage : BaseEntity
    {
        public string DutiesName { get; set; }
        /// <summary>
        /// 人员类别，见枚举(履约、变更、增配)
        /// </summary>
        public string PersonComeType { get; set; }
        /// <summary>
        /// 在场状态,见枚举PersonSceneStatus(在现场、不在现场)
        /// </summary>
        public int IsOnScene { get; set; }
        public DateTime EntryDate { get; set; }
        public string ProjectPosition { get; set; }
        public DateTime ExitDate { get; set; }
        public string ExitReason { get; set; }
        public bool IsHaveOwnerReplied { get; set; }
        public DateTime RepliedDate { get; set; }
        public bool RepliedResult { get; set; }
        public string RepliedSuggestion { get; set; }
        public string RepliedNumber { get; set; }
        /// <summary>
        /// 批复文件
        /// </summary>
        public string RepliedAttachment { get; set; }
        public string Description { get; set; }
    
        public virtual EM_ProjectBaseInfo EM_ProjectBaseInfo { get; set; }
        public virtual PM_PersonBaseInfo PM_PersonBaseInfo { get; set; }
    }
}
