//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using PSIMP.Business.BaseModel;

namespace PSIMP.Models
{
    public partial class PM_PersonWorkExperienceInfo : BaseEntity
    {
        public string CompanyName { get; set; }
        public string Character { get; set; }
        /// <summary>
        /// 规模
        /// </summary>
       // public string Scale { get; set; }
        public string SectorClass { get; set; }
        /// <summary>
        /// 参与监理的项目名称
        /// </summary>
        public string AtProject { get; set; }
        /// <summary>
        /// 职位名称，详见枚举:Position
        /// </summary>
        public string PositionName { get; set; }
        public DateTime? WorkStartDate { get; set; }
        public DateTime? WorkEndDate { get; set; }
        public decimal Salary { get; set; }
        /// <summary>
        /// 是否购买保险(true:购买，false：未购买)
        /// </summary>
        public bool IsHaveInsurance { get; set; }
        /// <summary>
        /// 见枚举ContractStatus,0:解除，1未解除
        /// </summary>
        public int ContractStatus { get; set; }
        public string WorkContent { get; set; }
        public string RefereesName { get; set; }
        public string RefereesPhoneNumber { get; set; }
        public string Remark { get; set; }
    
        public virtual PM_PersonBaseInfo PM_PersonBaseInfo { get; set; }
    }
}
