//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace PSIMP.Models
{
    using System;
    using System.Collections.Generic;
    using PSIMP.Business.BaseModel;
    
    public partial class AM_LaiWenRecordInfo : BaseEntity
    {
        
        public string LaiWenUnit { get; set; }
        /// <summary>
        /// 来文类别,详见枚举：LaiWenType
        /// </summary>
        public int LaiWenType { get; set; }
        /// <summary>
        /// 来文方式,见枚举(邮件、传真、信函)
        /// </summary>
        public int LaiWenMode { get; set; }
        public string FileSubject { get; set; }
        public string LaiWenSerialNumber { get; set; }
        public DateTime IncomeFileDate { get; set; }
        public int IncomeFileNum { get; set; }
        public string FileAttachment { get; set; }
        public string ProjectID { get; set; }
    
        public virtual ICollection<AM_LaiWenCircularizeDetail> AM_LaiWenCircularizeDetail { get; set; }
        public virtual ICollection<AM_LaiWenRepliedInfo> AM_LaiWenRepliedInfo { get; set; }
    }
}
