//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using PSIMP.Business.BaseModel;

namespace PSIMP.Models
{
    public partial class PM_PersonWorkExperienceInfo : BaseEntity
    {
       
        public System.DateTime WorkStartDate { get; set; }
        public System.DateTime WorkEndDate { get; set; }
        public string CompanyName { get; set; }
        public string Character { get; set; }
        public string SectorClass { get; set; }
        public string AtProject { get; set; }
        public string PositionName { get; set; }
        public decimal Salary { get; set; }
        public bool ContractStatus { get; set; }
        public string WorkContent { get; set; }
        public string RefereesName { get; set; }
        public string RefereesPhoneNumber { get; set; }
        public System.Guid PersonID { get; set; }
    
        public virtual PM_PersonBaseInfo PM_PersonBaseInfo { get; set; }
    }
}
